site_name: "My Obsidian Vault"
theme:
  name: material
nav:
  - "README": "README.md"
  - "Grammatik":
      - "Akkusativ": "Grammatik/Akkusativ.md"
      - "Dativ": "Grammatik/Dativ.md"
      - "Deklinationen": "Grammatik/Deklinationen.md"
      - "Futur": "Grammatik/Futur.md"
      - "Genitiv": "Grammatik/Genitiv.md"
      - "Instrumental": "Grammatik/Instrumental.md"
      - "Interrogativ Indefinit Negative Pronomen": "Grammatik/Interrogativ Indefinit Negative Pronomen.md"
      - "Lokativ": "Grammatik/Lokativ.md"
      - "Modalverbs": "Grammatik/Modalverbs.md"
      - "Nominativ": "Grammatik/Nominativ.md"
      - "Praepositionen": "Grammatik/Praepositionen.md"
      - "Steigerungen": "Grammatik/Steigerungen.md"
      - "Vokativ": "Grammatik/Vokativ.md"
  - "Karolina_lessons":
      - "archive": "Karolina_lessons/archive.md"
      - "lesson-2025-07-14": "Karolina_lessons/lesson-2025-07-14.md"
      - "lesson-2025-07-28  1": "Karolina_lessons/lesson-2025-07-28 _1.md"
      - "lesson-2025-07-28": "Karolina_lessons/lesson-2025-07-28.md"
  - "SlowCzech":
      - "Episode 32": "SlowCzech/Episode_32.md"
      - "Episode 45": "SlowCzech/Episode_45.md"
      - "Episode 46": "SlowCzech/Episode_46.md"
      - "Episode 47": "SlowCzech/Episode_47.md"
      - "Episode 48": "SlowCzech/Episode_48.md"
      - "Episode 49": "SlowCzech/Episode_49.md"
      - "Episode 50": "SlowCzech/Episode_50.md"
      - "Episode 59": "SlowCzech/Episode_59.md"
      - "Episode template": "SlowCzech/Episode_template.md"
      - "readme-slowczech": "SlowCzech/readme-slowczech.md"
  - "TextBook":
      - "Lekce 2": "TextBook/Lekce_2.md"
      - "Lekce 5": "TextBook/Lekce_5.md"
      - "Lekce 6": "TextBook/Lekce_6.md"
      - "readme-textbook": "TextBook/readme-textbook.md"
  - "VHSKurs":
      - "E1": "VHSKurs/E1.md"
      - "E2": "VHSKurs/E2.md"
      - "E3": "VHSKurs/E3.md"
      - "E4": "VHSKurs/E4.md"
      - "E5": "VHSKurs/E5.md"
      - "H2": "VHSKurs/H2.md"
      - "readme-vhs": "VHSKurs/readme-vhs.md"
  - "Vocabulary":
      - "autogenerated-vocabfile-Adjektiv": "Vocabulary/autogenerated-vocabfile-Adjektiv.md"
      - "autogenerated-vocabfile-Einkaufen-Essen": "Vocabulary/autogenerated-vocabfile-Einkaufen-Essen.md"
      - "autogenerated-vocabfile-Farbe-Kalender": "Vocabulary/autogenerated-vocabfile-Farbe-Kalender.md"
      - "autogenerated-vocabfile-Haushalt": "Vocabulary/autogenerated-vocabfile-Haushalt.md"
      - "autogenerated-vocabfile-Kalender": "Vocabulary/autogenerated-vocabfile-Kalender.md"
      - "autogenerated-vocabfile-Restaurant": "Vocabulary/autogenerated-vocabfile-Restaurant.md"
      - "autogenerated-vocabfile-Verb": "Vocabulary/autogenerated-vocabfile-Verb.md"
      - "Colors": "Vocabulary/Colors.md"
      - "Kuchyně": "Vocabulary/Kuchyně.md"
      - "Months and Seasons": "Vocabulary/Months and Seasons.md"
      - "Rodina": "Vocabulary/Rodina.md"
      - "Weekdays": "Vocabulary/Weekdays.md"
